controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
# config/routes.yaml
search_by_city:
    path: '/search'
    controller: 'App\Controller\PropertyController::searchByCity'
